### ISSUE TITLE
Link sharing to Unalix activity is not working

### ISSUE THREAD

**Issue by archtur** [AmanoTeam/UnalixAndroid#3]
When I share a link e.g. from Fennec to the CleanURL activity I would expect 
1. to have the cleaned URL afterwards in the clipboard
2. or to get a share menu again where I can share the cleaned link afterwards.

Steps to reproduce:
1. install Unalix 0.6.1 from F-Droid (https://f-droid.org/packages/com.amanoteam.unalix)
2. open Browser, choose an amazon article an share the tabs link to Unalix CleanURL activity
3. after choosing the activity, nothing happens

When I manually paste the amazon article link to the input field in Unalix and click the cleanup button, it works.

The content that is shared from a Browser is e.g. "https://www.amazon.de/dp/B09JTT1JTW/ref=mp_s_a_1_3?crid=18OR25GFYTQGZ&keywords=feuerschwanz+memento+mori&qid=1643646649&sprefix=feuerschwan%2Caps%2C164&sr=8-3". I also tested sharing this link from Text fields of other apps (same result)

I use Android 10.

**Comment by alissonlauffer** [comment]
~By the way, the crash in the "Unshort URL" option still happens, since it is being caused by a different issue (most specifically a segmentation fault at our native library). I will try to debug it soon.~

Edit: Nevermind, it was a Nim issue and has been fixed in newer Nim releases (I'm still building the native library with Nim 1.4.8 locally :P).

**Comment by archtur** [comment]
@alissonlauffer Thank you for this information. Please link the corresponding update ticket here.

And thank you all for the reactive approach regarding this issue.

**Comment by alissonlauffer** [comment]
> Please link the corresponding update ticket here.

Update ticket of Nim? This was an Android compatibility issue present in older Nim releases (like 1.4.8) that has been fixed at the current releases. Unalix is "officially" built with Nim 1.6.1, so this issue was not present in "official" builds.
My current environment has Nim 1.4.8, so that's why I was getting crashes.

> for the reactive approach regarding this issue.

Reactive approach?

**Comment by archtur** [comment]
ok, thank you.

> Reactive approach?

Yes, I meant your way of working to fast react to my request. Thank you for that. 
I could test that with the latest release on F-Droid `0.7` already and it is working very well.
